### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by KELETU66666** [Zokonius/planar-artifice#37]
---- Minecraft Crash Report ----
// I let you down. Sorry :(
​
Time: 2022-02-10 14:42:38 CST
Description: Rendering screen
​
java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block planarartifice:alkimium_smeltery_adaminite, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
    at leppa.planarartifice.blocks.BlockAlkimiumSmeltery.func_176203_a(BlockAlkimiumSmeltery.java:188)
    at weissmoon.core.client.event.ClientEvents.tooltipEvent(ClientEvents.java:36)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1190_ClientEvents_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
    at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:737)
    at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:684)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
​
​
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
​
-- Screen render details --
  Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
  Mouse location: Scaled: (176, 171). Absolute: (706, 317)
  Screen size: Scaled: (480, 251). Absolute: (1920, 1001). Scale factor of 4
​
-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['keletu'/1, l='MpServer', x=307.13, y=76.00, z=556.67]]
  Chunk stats: MultiplayerChunkCache: 531, 531
  Level seed: 0
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (311,64,564), Chunk: (at 7,4,4 in 19,35; contains blocks 304,0,560 to 319,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
  Level time: 1475 game time, 1475 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 66 total; [EntityPlayerSP['keletu'/1, l='MpServer', x=307.13, y=76.00, z=556.67], EntityLatchedRenderer['??'/3, l='MpServer', x=8.50, y=65.00, z=8.50], EntityPig['?'/4, l='MpServer', x=326.51, y=64.00, z=567.73], EntitySpider['??'/388, l='MpServer', x=311.50, y=15.00, z=583.50], EntitySquid['??'/6, l='MpServer', x=321.39, y=62.27, z=532.89], EntitySkeleton['??'/785, l='MpServer', x=350.50, y=17.00, z=574.50], EntitySpider['??'/786, l='MpServer', x=346.50, y=17.00, z=575.50], EntitySpider['??'/787, l='MpServer', x=350.94, y=17.00, z=576.07], EntitySquid['??'/22, l='MpServer', x=282.54, y=62.59, z=547.03], EntitySkeleton['??'/278, l='MpServer', x=359.50, y=19.00, z=618.50], EntityZombie['??'/406, l='MpServer', x=333.50, y=20.00, z=630.50], EntitySquid['??'/23, l='MpServer', x=293.82, y=58.63, z=541.87], EntitySkeleton['??'/407, l='MpServer', x=383.50, y=31.00, z=622.50], EntitySquid['??'/24, l='MpServer', x=277.56, y=59.53, z=547.50], EntitySquid['??'/25, l='MpServer', x=278.54, y=60.26, z=566.60], EntitySpider['??'/793, l='MpServer', x=368.50, y=21.00, z=622.50], EntityBat['??'/153, l='MpServer', x=383.68, y=31.07, z=621.00], EntitySquid['??'/26, l='MpServer', x=289.29, y=51.05, z=538.18], EntityZombie['??'/794, l='MpServer', x=366.50, y=21.00, z=622.50], EntityBat['??'/539, l='MpServer', x=349.66, y=17.02, z=575.21], EntitySquid['??'/28, l='MpServer', x=281.23, y=51.32, z=547.57], EntitySquid['??'/29, l='MpServer', x=299.60, y=51.50, z=544.60], EntityCreeper['???'/797, l='MpServer', x=310.50, y=15.00, z=583.50], EntityEnderman['???'/414, l='MpServer', x=347.50, y=13.00, z=622.50], EntityZombie['??'/287, l='MpServer', x=348.50, y=17.00, z=573.50], EntityEnderman['???'/415, l='MpServer', x=347.50, y=13.00, z=623.50], EntitySkeleton['??'/416, l='MpServer', x=346.30, y=13.00, z=620.34], EntityCreeper['???'/290, l='MpServer', x=386.50, y=25.00, z=602.50], EntityBat['??'/677, l='MpServer', x=328.94, y=20.05, z=626.41], EntityCreeper['???'/680, l='MpServer', x=328.50, y=15.00, z=633.50], EntityBat['??'/424, l='MpServer', x=384.77, y=27.79, z=599.37], EntityZombie['??'/816, l='MpServer', x=315.45, y=42.16, z=554.60], EntityCreeper['???'/305, l='MpServer', x=327.50, y=21.00, z=576.50], EntitySkeleton['??'/563, l='MpServer', x=318.50, y=17.00, z=578.50], EntityCreeper['???'/308, l='MpServer', x=271.50, y=15.00, z=507.50], EntitySlime['???'/564, l='MpServer', x=336.71, y=20.10, z=578.30], EntitySkeleton['??'/694, l='MpServer', x=297.50, y=17.00, z=522.50], EntityZombie['??'/56, l='MpServer', x=300.70, y=20.66, z=511.30], EntityEnderman['???'/57, l='MpServer', x=300.50, y=20.00, z=508.50], EntityZombie['??'/314, l='MpServer', x=318.50, y=17.00, z=586.50], EntitySkeleton['??'/315, l='MpServer', x=316.50, y=17.00, z=584.50], EntityCreeper['???'/65, l='MpServer', x=262.50, y=28.00, z=568.50], EntityBat['??'/578, l='MpServer', x=302.75, y=21.04, z=485.52], EntityEnderman['???'/326, l='MpServer', x=375.50, y=16.00, z=630.50], EntityBat['??'/454, l='MpServer', x=288.25, y=20.10, z=476.75], EntityBat['??'/583, l='MpServer', x=304.29, y=19.12, z=484.07], EntityZombie['??'/333, l='MpServer', x=322.50, y=19.00, z=579.50], EntitySkeleton['??'/334, l='MpServer', x=357.50, y=18.00, z=619.50], EntityZombie['??'/719, l='MpServer', x=333.18, y=20.00, z=631.45], EntityZombie['??'/82, l='MpServer', x=319.72, y=18.00, z=586.54], EntityZombie['??'/210, l='MpServer', x=337.50, y=19.00, z=579.24], EntitySkeleton['??'/850, l='MpServer', x=345.73, y=13.00, z=621.45], EntityCreeper['???'/212, l='MpServer', x=333.48, y=19.00, z=578.69], EntityBat['??'/859, l='MpServer', x=330.54, y=20.67, z=627.53], EntitySkeleton['??'/480, l='MpServer', x=383.50, y=27.00, z=597.50], EntityBat['??'/869, l='MpServer', x=333.47, y=20.40, z=628.81], EntityBat['??'/614, l='MpServer', x=345.74, y=18.47, z=575.32], EntityBat['??'/615, l='MpServer', x=334.15, y=20.10, z=576.46], EntityCreeper['???'/233, l='MpServer', x=287.54, y=12.00, z=480.77], EntityZombie['??'/362, l='MpServer', x=367.40, y=21.00, z=623.08], EntitySpider['??'/876, l='MpServer', x=373.50, y=21.00, z=622.50], EntityCreeper['???'/365, l='MpServer', x=370.18, y=21.00, z=622.47], EntityCreeper['???'/501, l='MpServer', x=284.50, y=19.00, z=478.50], EntitySkeleton['??'/629, l='MpServer', x=385.50, y=25.00, z=598.50], EntityCreeper['???'/634, l='MpServer', x=347.50, y=16.00, z=579.50], EntityCreeper['???'/383, l='MpServer', x=315.50, y=15.00, z=568.50]]
  Retry entities: 1 total; [EntityLatchedRenderer['??'/3, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Integrated singleplayer server
​
-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_232, BellSoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode),
  Memory: 4522917896 bytes (4313 MB) / 6325010432 bytes (6032 MB) up to 6979321856 bytes (6656 MB)
  JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6656m
  IntCache: cache: 0, tcache: 7, allocated: 11, tallocated: 96
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 78 mods loaded, 78 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version              | Source                                                      | Signature                                |
       |:------ |:-------------------- |:-------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2               | minecraft.jar                                               | None                                     |
       | LCHIJA | mcp                  | 9.42                 | minecraft.jar                                               | None                                     |
       | LCHIJA | FML                  | 8.0.99.99            | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2860         | forge-1.12.2-14.23.5.2860.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | anothercommonbugfix  | 1.2.5                | minecraft.jar                                               | None                                     |
       | LCHIJA | jecharacters         | 1.12.0-3.5.1         | [??????] JustEnoughCharacters-1.12.0-3.5.1.jar              | None                                     |
       | LCHIJA | smoothfontcore       | mc1.12.2-2.1.2       | minecraft.jar                                               | None                                     |
       | LCHIJA | smoothfont           | mc1.12.2-2.1.2       | SmoothFont-mc1.12.2-2.1.2.jar                               | None                                     |
       | LCHIJA | waila                | 1.8.26               | [Here's What You're Looking At] Hwyla-1.8.26-B41_1.12.2.jar | None                                     |
       | LCHIJA | inventorytweaks      | 1.64+dev.151.822d839 | [R???] InventoryTweaks-1.64+dev.151.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | wanionlib            | 1.12.2-2.5           | [Wanion Lib] WanionLib-1.12.2-2.5.jar                       | None                                     |
       | LCHIJA | realfilingcabinet    | 0.2.0.21             | [?????] realfilingcabinet-1.12-0.2.0.21.jar                 | None                                     |
       | LCHIJA | baubles              | 1.5.2                | [?????]Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-150           | [????] VanillaFix-1.0.10-150.jar                            | None                                     |
       | LCHIJA | ftbbackups           | 1.1.0.1              | [??]FTBBackups-1.1.0.1.jar                                  | None                                     |
       | LCHIJA | thaumcraft           | 6.1.BETA26           | [????6]Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
       | LCHIJA | lostmagic            | 1.0                  | [????]lostmagic-1.0.2.jar                                   | None                                     |
       | LCHIJA | journeymap           | 1.12.2-5.7.1         | [????] journeymap-1.12.2-5.7.1.jar                          | None                                     |
       | LCHIJA | ironchest            | 1.12.2-7.0.67.844    | [????]ironchest-1.12.2-7.0.72.847.jar                       | None                                     |
       | LCHIJA | crafttweaker         | 4.1.20               | CraftTweaker2-1.12-4.1.20.662.jar                           | None                                     |
       | LCHIJA | mtlib                | 3.0.7                | MTLib-3.0.7.jar                                             | None                                     |
       | LCHIJA | modtweaker           | 4.0.19               | modtweaker-4.0.20.5.jar                                     | None                                     |
       | LCHIJA | jei                  | 4.16.1.301           | jei_1.12.2-4.16.1.301.jar                                   | None                                     |
       | LCHIJA | botania              | r1.10-364            | Botania r1.10-364.4.jar                                     | None                                     |
       | LCHIJA | hammercore           | 2.0.6.31             | HammerLib-1.12.2-2.0.6.31.jar                               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | botanicadds          | 12.2.6               | [?????] BotanicAdditions-1.12.2-12.2.6.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | thaumicjei           | 1.6.0                | [??6?JEI??]ThaumicJEI-1.12.2-1.6.0-27.jar                   | None                                     |
       | LCHIJA | rustic               | 1.1.7                | rustic-1.1.7.jar                                            | None                                     |
       | LCHIJA | rusticthaumaturgy    | 4.4a                 | [????]Rustic+Thaumaturgy-4.4a.jar                           | None                                     |
       | LCHIJA | thaumicperiphery     | 0.3.1                | [????]thaumicperiphery-0.3.1.jar                            | None                                     |
       | LCHIJA | thaumicwonders       | 1.8.2                | [????]thaumicwonders-1.8.2.jar                              | None                                     |
       | LCHIJA | thaumictinkerer      | 1.12.2-5.0-620a0c5   | [????] thaumictinkerer-1.12.2-5.0-620a0c5.jar               | None                                     |
       | LCHIJA | thaumicbrewing       | 1.0.2                | [????]thaumicbrewing-1.0.2.jar                              | None                                     |
       | LCHIJA | thaumadditions       | 12.6.7               | [???????] ThaumicAdditions-1.12.2-12.6.7.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | custommainmenu       | 2.0.9.1              | [??????] CustomMainMenu-MC1.12.2-2.0.9.1.jar                | None                                     |
       | LCHIJA | testdummy            | 1.12                 | [????] MmmMmmMmmMmm-1.12-1.14.jar                           | None                                     |
       | LCHIJA | biomesoplenty        | 7.0.1.2444           | [??????] BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
       | LCHIJA | ic2                  | 2.8.1001             | IC2Classic+1.12-1.5.5.2.1.jar                               | None                                     |
       | LCHIJA | forestry             | 5.8.2.422            | forestry_1.12.2-5.8.2.422.jar                               | None                                     |
       | LCHIJA | magicbees            | 1.0                  | [????]MagicBees-1.12.2-3.2.25.jar                           | None                                     |
       | LCHIJA | mousetweaks          | 2.10.1               | [????] MouseTweaks-2.10.1-mc1.12.2.jar                      | None                                     |
       | LCHIJA | ctm                  | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                                   | None                                     |
       | LCHIJA | appliedenergistics2  | rv6-stable-7         | appliedenergistics2-rv6-stable-7.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | base                 | 3.14.0               | base-1.12.2-3.14.0.jar                                      | None                                     |
       | LCHIJA | patchouli            | 1.0-23.6             | Patchouli-1.0-23.6.jar                                      | None                                     |
       | LCHIJA | bewitchment          | 0.22.63              | bewitchment-1.12.2-0.0.22.64.jar                            | None                                     |
       | LCHIJA | ctgui                | 1.0.0                | CraftTweaker2-1.12-4.1.20.662.jar                           | None                                     |
       | LCHIJA | crafttweakerjei      | 2.0.3                | CraftTweaker2-1.12-4.1.20.662.jar                           | None                                     |
       | LCHIJA | crafttweakersync     | 1.1                  | CraftTweakerSync.jar                                        | None                                     |
       | LCHIJA | dummycore            | 2.4.112.5.           | DummyCoreUnofficial-2.4.112.5.jar                           | None                                     |
       | LCHIJA | weisscore            | 0.1.1                | WeissCore-1.12.2-0.1.1-16.jar                               | None                                     |
       | LCHIJA | welectromagic        | 0.0.9                | ElectroMagicToolsIC2C-1.12.2-0.0.9-12.jar                   | None                                     |
       | LCHIJA | twilightforest       | 3.11.1021            | twilightforest-1.12.2-3.11.1021-universal.jar               | None                                     |
       | LCHIJA | immersiveengineering | 0.12-98              | [????] ImmersiveEngineering-0.12-98.jar                     | None                                     |
       | LCHIJA | engineeredgolems     | 1.2                  | Engineered Golems-1.2a.jar                                  | None                                     |
       | LCHIJA | ea                   | 1.0.1                | ExpandedArcanum-1.0.1.jar                                   | None                                     |
       | LCHIJA | ftblib               | 5.4.7.2              | FTBLib-5.4.7.2.jar                                          | None                                     |
       | LCHIJA | ftbutilities         | 5.4.1.131            | FTBUtilities-5.4.1.131.jar                                  | None                                     |
       | LCHIJA | itemfilters          | 1.0.4.2              | ItemFilters-1.0.4.2.jar                                     | None                                     |
       | LCHIJA | ftbquests            | 1202.9.0.15          | FTBQuests-1202.9.0.15.jar                                   | None                                     |
       | LCHIJA | ftbmoney             | 1.2.0.47             | FTBMoney-1.2.0.47.jar                                       | None                                     |
       | LCHIJA | ic2-classic-spmod    | 0.0.0.0              | IC2Classic+1.12-1.5.5.2.1.jar                               | None                                     |
       | LCHIJA | ichunutil            | 7.2.2                | iChunUtil-1.12.2-7.2.2.jar                                  | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | itlt                 | 1.0.4                | itlt-1.12.x-1.0.4.jar                                       | None                                     |
       | LCHIJA | jeibees              | 0.9.0.5              | jei??.jar                                                   | None                                     |
       | LCHIJA | planarartifice       | 1.1.0                | planarartifice-1.1.6.jar                                    | None                                     |
       | LCHIJA | resourceloader       | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3???1.12?1.12.1?.jar            | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | surge                | 2.0.79               | Surge-1.12.2-2.0.79.jar                                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tcresearchpatcher    | 1.12.2-1.1.3         | ThaumcraftResearchPatcher-1.12.2-1.1.3.jar                  | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicaugmentation  | 1.12.2-2.1.5         | ThaumicAugmentation-1.12.2-2.1.4.jar                        | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicbases         | 3.3.500.6r           | thaumicbases-fixed-3.3.500.6.2r.jar                         | None                                     |
       | LCHIJA | thaumicenergistics   | 2.2.3                | thaumicenergistics-v2.2.3-alex811-fork-SNAPSHOT-2.jar       | None                                     |
       | LCHIJA | tcinventoryscan      | 2.0.10               | ThaumicInventoryScanning_1.12.2-2.0.10.jar                  | None                                     |
       | LCHIJA | tips                 | 1.0.9                | Tips-1.12.2-1.0.9.jar                                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | wailaharvestability  | 1.1.12               | WailaHarvestability-mc1.12-1.1.12.jar                       | None                                     |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.6         | phosphor-1.12.2-0.2.6+build50-universal.jar                 | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | unidict              | 1.12.2-3.0.8         | [????] UniDict-1.12.2-3.0.8.jar                             | None                                     |
       | LCHIJA | weisscoreterminal    | 0.1.1                | WeissCore-1.12.2-0.1.1-16.jar                               | None                                     |
  Loaded coremods (and transformers): IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
                                        thecodex6824.tcresearchpatcher.Transformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      AnotherCommonBugFix ([BUG??]AnotherCommonBugFix.jar)
                                        com.anotherera.core.ACBFClassTransformer
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
                                        
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      VanillaFixLoadingPlugin ([????] VanillaFix-1.0.10-150.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3???1.12?1.12.1?.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      HCASM (HammerLib-1.12.2-2.0.6.31.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.4.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      Inventory Tweaks Coremod ([R???] InventoryTweaks-1.64+dev.151.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      JechCore ([??????] JustEnoughCharacters-1.12.0-3.5.1.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.9664' Renderer: 'Intel(R) UHD Graphics'
  HammerCore Debug Information: Dependent Mods:
                                -Botanic Additions (botanicadds) @ 12.2.6
                                -Thaumic Additions: Reconstructed (thaumadditions) @ 12.6.7
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Patchouli open book context: n/a
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore'
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Planar Artifice (planarartifice), WeissCore (weisscore), WeissCoreterminal (weisscoreterminal)
  Launched Version: magic pack
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 27.20.100.9664, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: ???? (??)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by Pulz-TCP** [comment]
FWIW: I encountered this issue with 1.3.1 and can replicate simply by starting a new **singleplayer** world, enabling cheats and using JEI to obtain planarartifice:alkimium_smeltery

After updating to 1.4.0-pre7, I was able to spawn the item and place it with no issue.

I have a couple of **server** players (1.3.1) who were crashing the server just by possessing the item in their inventory.

When I have rolled out the 1.4.0-pre7 update, I will post back to confirm if this has, in my case, resolved the problem.

**Comment by Pulz-TCP** [comment]
As per the above, having pushed out 1.4.0-pre7 over 1.3.1, I am no longer getting the error specified in this issue.

**Comment by Pulz-TCP** [comment]
Nevermind, the issue has started up again.
https://gist.github.com/Pulz-TCP/d6da6106a852cd1270533070cd90631b
