### ISSUE TITLE
the game can't launch

### ISSUE THREAD

**Issue by EnderAvaritia** [Zokonius/planar-artifice#39]
it seems load a recipe should not be loaded 
here is the crash report
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-02-10 15:53:06 GMT+08:00
Description: Initializing game

java.lang.NoClassDefFoundError: soot/Registry
    at leppa.planarartifice.registry.PARecipes.registerCrucibleRecipes(PARecipes.java:146)
    at leppa.planarartifice.registry.PARecipes.registerRecipes(PARecipes.java:47)
    at leppa.planarartifice.registry.Registrar.registerRecipes(Registrar.java:31)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_817_Registrar_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(ModMixinLoader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: soot.Registry
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 20 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_321, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 11885099528 bytes (11334 MB) / 14562623488 bytes (13888 MB) up to 17179869184 bytes (16384 MB)
  JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx16384m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 167 mods loaded, 167 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                        | Version              | Source                                                | Signature                                |
       |:----- |:------------------------- |:-------------------- |:----------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                 | 1.12.2               | minecraft.jar                                         | None                                     |
       | LCH   | mcp                       | 9.42                 | minecraft.jar                                         | None                                     |
       | LCH   | FML                       | 8.0.99.99            | forge-1.12.2-14.23.5.2860.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                     | 14.23.5.2860         | forge-1.12.2-14.23.5.2860.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | anothercommonbugfix       | 1.2.5                | minecraft.jar                                         | None                                     |
       | LCH   | ivtoolkit                 | 1.3.3-1.12           | minecraft.jar                                         | None                                     |
       | LCH   | jecharacters              | 1.12.0-3.5.1         | JustEnoughCharacters-1.12.0-3.5.1.jar                 | None                                     |
       | LCH   | smoothfontcore            | mc1.12.2-2.1.2       | minecraft.jar                                         | None                                     |
       | LCH   | mixinbooter               | 3.2                  | minecraft.jar                                         | None                                     |
       | LCH   | bnbgamingcore             | 0.12.0               | minecraft.jar                                         | None                                     |
       | LCH   | opencomputers|core        | 1.7.5.192            | minecraft.jar                                         | None                                     |
       | LCH   | botania_tweaks_core       | -100                 | minecraft.jar                                         | None                                     |
       | LCH   | smoothfont                | mc1.12.2-2.1.2       | SmoothFont-mc1.12.2-2.1.2.jar                         | None                                     |
       | LCH   | ctm                       | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
       | LCH   | stackup                   | 0.2.5                | StackUp-0.2.5.jar                                     | None                                     |
       | LCH   | appliedenergistics2       | rv6-stable-7         | appliedenergistics2-rv6-stable-7.jar                  | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCH   | baubles                   | 1.5.2                | Baubles-1.12-1.5.2.jar                                | None                                     |
       | LCH   | gbook_snapshot            | 2.9.1.s5             | Guidebook-1.12.2-2.9.1.s5.jar                         | None                                     |
       | LCH   | thaumcraft                | 6.1.BETA26           | Thaumcraft-1.12.2-6.1.BETA26.jar                      | None                                     |
       | LCH   | arcanearchives            | 0.2.0.25-mixins8     | arcanearchives-0.2.0.25-mixins8.jar                   | None                                     |
       | LCH   | crafttweaker              | 4.1.20               | CraftTweaker2-1.12-4.1.20.673.jar                     | None                                     |
       | LCH   | mtlib                     | 3.0.7                | MTLib-3.0.7.jar                                       | None                                     |
       | LCH   | modtweaker                | 4.0.19               | modtweaker-4.0.20.5.jar                               | None                                     |
       | LCH   | bookshelf                 | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | gamestages                | 2.0.123              | GameStages-1.12.2-2.0.123.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | recipestages              | 1.1.3                | RecipeStages-1.1.3.8.jar                              | None                                     |
       | LCH   | primitivecrafting         | 1.12.2               | primitivecrafting-1.12.2-1.4.4.7.jar                  | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCH   | jei                       | 4.16.1.301           | jei_1.12.2-4.16.1.301.jar                             | None                                     |
       | LCH   | athenaeum                 | 1.12.2-1.19.5        | athenaeum-1.12.2-1.19.5.jar                           | None                                     |
       | LCH   | mousetweaks               | 2.10.1               | MouseTweaks-2.10.1-mc1.12.2.jar                       | None                                     |
       | LCH   | artisanworktables         | 1.12.2-1.24.2        | artisanworktables-1.12.2-1.24.2.jar                   | None                                     |
       | LCH   | astralsorcery             | 1.10.27              | astralsorcery-1.12.2-1.10.27.jar                      | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | astrosorc                 | 1.1.3                | astrologicalsorcery-1.12.2-1.1.3.jar                  | None                                     |
       | LCH   | quark                     | r1.6-179             | Quark-r1.6-179.jar                                    | None                                     |
       | LCH   | autoreglib                | 1.3-32               | AutoRegLib-1.3-32.jar                                 | None                                     |
       | LCH   | codechickenlib            | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | avaritia                  | 3.3.0                | Avaritia-1.12.2-3.3.0.37-universal.jar                | None                                     |
       | LCH   | botania_tweaks            | 1.9.1                | botaniatweaks-1.9.1.jar                               | None                                     |
       | LCH   | botania                   | r1.10-364            | Botania r1.10-364.4.jar                               | None                                     |
       | LCH   | avaritiatweaks            | @VERSION@            | Avaritia's+Complement-1.12.2-1.4.jar                  | None                                     |
       | LCH   | wanionlib                 | 1.12.2-2.9           | WanionLib-1.12.2-2.9.jar                              | None                                     |
       | LCH   | avaritiaddons             | 1.12.2-1.6           | Avaritiaddons-1.12.2-1.6.jar                          | None                                     |
       | LCH   | avaritiarecipemaker       | 1.0.0                | avaritiarecipemaker-1.0.0.jar                         | None                                     |
       | LCH   | base                      | 3.14.0               | base-1.12.2-3.14.0.jar                                | None                                     |
       | LCH   | betterbuilderswands       | 0.11.1               | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar       | None                                     |
       | LCH   | bnbgaminglib              | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                        | None                                     |
       | LCH   | hammercore                | 2.0.6.31             | HammerLib-1.12.2-2.0.6.31.jar                         | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | botanicadds               | 12.2.6               | BotanicAdditions-1.12.2-12.2.6.jar                    | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | brazier                   | 1.2.0                | brazier-1.2.0.jar                                     | None                                     |
       | LCH   | capsule                   | 1.12.2-3.4.76        | Capsule-1.12.2-3.4.76.jar                             | None                                     |
       | LCH   | cd4017be_lib              | 6.5.1                | CD4017BE_lib-1.12.2-6.5.1.jar                         | None                                     |
       | LCH   | chisel                    | MC1.12.2-1.0.2.45    | Chisel-MC1.12.2-1.0.2.45.jar                          | None                                     |
       | LCH   | chiselsandbits            | 14.33                | chiselsandbits-14.33.jar                              | None                                     |
       | LCH   | cyclopscore               | 1.6.7                | CyclopsCore-1.12.2-1.6.7.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | commoncapabilities        | 2.4.8                | CommonCapabilities-1.12.2-2.4.8.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | compactmachines3          | 3.0.18               | compactmachines3-1.12.2-3.0.18-b278.jar               | None                                     |
       | LCH   | contenttweaker            | 1.12.2-4.10.0        | ContentTweaker-1.12.2-4.10.0.jar                      | None                                     |
       | LCH   | ctgui                     | 1.0.0                | CraftTweaker2-1.12-4.1.20.673.jar                     | None                                     |
       | LCH   | crafttweakerjei           | 2.0.3                | CraftTweaker2-1.12-4.1.20.673.jar                     | None                                     |
       | LCH   | crafttweakersync          | 1.1                  | CraftTweakerSync.jar                                  | None                                     |
       | LCH   | crimsonwarfare            | 1.5                  | crimsonwarfare-1.5.jar                                | None                                     |
       | LCH   | cucumber                  | 1.1.3                | Cucumber-1.12.2-1.1.3.jar                             | None                                     |
       | LCH   | dimensionalcontrol        | 2.13.0               | DimensionalControl-1.12.2-2.13.0.jar                  | None                                     |
       | LCH   | dimstages                 | 2.0.23               | DimensionStages-1.12.2-2.0.23.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | dummycore                 | 2.4.112.5.           | DummyCoreUnofficial-2.4.112.5.jar                     | None                                     |
       | LCH   | ebwizardry                | 4.3.4                | ElectroblobsWizardry-4.3.4-MC1.12.2.jar               | None                                     |
       | LCH   | mysticalmechanics         | 0.18                 | Mystical Mechanics-0.18.jar                           | None                                     |
       | LCH   | embers                    | 1.18                 | EmbersRekindled-1.18.jar                              | None                                     |
       | LCH   | enchantingwiththaumcraft  | 1.3                  | enchantingwiththaumcraft-1.3.jar                      | None                                     |
       | LCH   | immersiveengineering      | 0.12-98              | ImmersiveEngineering-0.12-98.jar                      | None                                     |
       | LCH   | engineeredgolems          | 1.2                  | Engineered Golems-1.2a.jar                            | None                                     |
       | LCH   | evilcraft                 | 0.10.78              | EvilCraft-1.12.2-0.10.78.jar                          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | forestry                  | 5.8.2.422            | forestry_1.12.2-5.8.2.422.jar                         | None                                     |
       | LCH   | evilcraftcompat           | 1.0.0                | EvilCraft-1.12.2-0.10.78.jar                          | None                                     |
       | LCH   | ea                        | 1.0.1                | ExpandedArcanum-1.0.1.jar                             | None                                     |
       | LCH   | extendedcrafting          | 1.5.6                | ExtendedCrafting-1.12.2-1.5.6.jar                     | None                                     |
       | LCH   | externaltweaker           | 0.3                  | externaltweaker-1.12-0.3.jar                          | None                                     |
       | LCH   | fastleafdecay             | v14                  | FastLeafDecay-v14.jar                                 | None                                     |
       | LCH   | forgelin                  | 1.8.4                | Forgelin-1.8.4.jar                                    | None                                     |
       | LCH   | ftbultimine               | 1202.3.5             | ftb-ultimine-1202.3.5.jar                             | None                                     |
       | LCH   | ftbbackups                | 1.1.0.1              | FTBBackups-1.1.0.1.jar                                | None                                     |
       | LCH   | ftblib                    | 5.4.7.2              | FTBLib-5.4.7.2.jar                                    | None                                     |
       | LCH   | ftbutilities              | 5.4.1.131            | FTBUtilities-5.4.1.131.jar                            | None                                     |
       | LCH   | itemfilters               | 1.0.4.2              | ItemFilters-1.0.4.2.jar                               | None                                     |
       | LCH   | ftbquests                 | 1202.9.0.15          | FTBQuests-1202.9.0.15.jar                             | None                                     |
       | LCH   | ftbmoney                  | 1.2.0.47             | FTBMoney-1.2.0.47.jar                                 | None                                     |
       | LCH   | ftgumod                   | 1.12.2-b1.4.3        | ftgu-1.12.2-b1.4.3.jar                                | None                                     |
       | LCH   | fw                        | 1.6.0                | FullscreenWindowed-1.12-1.6.0.jar                     | None                                     |
       | LCH   | glacidus                  | 1.2.1                | Glacidus-1.12.2-v1.2.1.jar                            | None                                     |
       | LCH   | mcjtylib_ng               | 3.5.4                | mcjtylib-1.12-3.5.4.jar                               | None                                     |
       | LCH   | modularmachinery          | 1.11.1               | modularmachinery-1.12.2-1.11.1.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | patchouli                 | 1.0-23.6             | Patchouli-1.0-23.6.jar                                | None                                     |
       | LCH   | naturesaura               | 18.1                 | NaturesAura-18.1.jar                                  | None                                     |
       | LCH   | gugu-utils                | 0.8.1.2              | gugu-utils-0.8.1.2.jar                                | None                                     |
       | LCH   | waila                     | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
       | LCH   | integrateddynamics        | 1.1.11               | IntegratedDynamics-1.12.2-1.1.11.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integrated_proxy          | 1.0.14               | integrated_proxy-1.12-1.0.14.jar                      | None                                     |
       | LCH   | integratedcrafting        | 1.0.10               | IntegratedCrafting-1.12.2-1.0.10.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integrateddynamicscompat  | 1.0.0                | IntegratedDynamics-1.12.2-1.1.11.jar                  | None                                     |
       | LCH   | integratednbt             | 1.2.2                | integratednbt-1.2.2.jar                               | None                                     |
       | LCH   | integratedrest            | 1.1.1                | IntegratedREST-1.12.2-1.1.1.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integratedterminals       | 1.0.14               | IntegratedTerminals-1.12.2-1.0.14.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integratedterminalscompat | 1.0.0                | IntegratedTerminals-1.12.2-1.0.14.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integratedtunnels         | 1.6.14               | IntegratedTunnels-1.12.2-1.6.14.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integratedtunnelscompat   | 1.0.0                | IntegratedTunnels-1.12.2-1.6.14.jar                   | None                                     |
       | LCH   | inventorytweaks           | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | inworldcrafting           | 1.12.2-1.2.0         | inworldcrafting-1.12.2-1.2.0-universal.jar            | None                                     |
       | LCH   | itemstages                | 2.0.49               | ItemStages-1.12.2-2.0.49.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | jeid                      | 1.0.4-SNAPSHOT       | JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar                 | None                                     |
       | LCH   | librarianlib              | 4.22                 | librarianlib-1.12.2-4.22.jar                          | None                                     |
       | LCH   | loottweaker               | 0.3.0                | LootTweaker-0.3.0+MC1.12.2.jar                        | None                                     |
       | LCH   | lostmagic                 | 1.0                  | lostmagic-1.0.2.jar                                   | None                                     |
       | LCH   | magicbees                 | 1.0                  | MagicBees-1.12.2-3.2.25.jar                           | None                                     |
       | LCH   | mtrm                      | 1.2.2.30             | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar            | None                                     |
       | LCH   | modularcontroller         | 1.3.1                | ModularController-1.3.1.jar                           | None                                     |
       | LCH   | modularassembly           | 1.0.2                | ModularAssembly-1.12.2-1.0.2.jar                      | None                                     |
       | LCH   | modularmagic              | 1.6.2                | modularmagic-1.6.2.jar                                | None                                     |
       | LCH   | morecharcoal              | 1.12.2-10            | morecharcoal-1.12.2-10.jar                            | None                                     |
       | LCH   | moretweaker               | 1.0.19               | MoreTweaker-1.0.19.jar                                | None                                     |
       | LCH   | llibrary                  | 1.7.20               | llibrary-1.7.20-1.12.2.jar                            | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | mowziesmobs               | 1.5.8                | mowziesmobs-1.5.8.jar                                 | None                                     |
       | LCH   | mystcraft                 | 0.13.7.06            | mystcraft-1.12.2-0.13.7.06.jar                        | None                                     |
       | LCH   | thaumicperiphery          | 0.3.1                | thaumicperiphery-0.3.1.jar                            | None                                     |
       | LCH   | mystgears                 | 1.1.7                | mystgears-1.1.7.jar                                   | None                                     |
       | LCH   | naturalpledge             | 3.0.3                | NaturalPledge-r3.1.2.jar                              | None                                     |
       | LCH   | opencomputers             | 1.7.5.192            | OpenComputers-MC1.12.2-1.7.5.192.jar                  | None                                     |
       | LCH   | parrotpower               | 1.12.2               | parrotpower-1.3.4.jar                                 | None                                     |
       | LCH   | planarartifice            | 1.1.0                | planarartifice-1.1.6.jar                              | None                                     |
       | LCH   | pouchofunknown            | 1.9                  | pouchofunknown-1.9.jar                                | None                                     |
       | LCH   | reccomplex                | 1.4.8.2              | RecurrentComplex-1.4.8.2.jar                          | None                                     |
       | LCH   | rs_ctr                    | 0.3.1                | RedstoneControl-1.12.2-0.3.1.3.jar                    | None                                     |
       | LCH   | redstoneflux              | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar               | None                                     |
       | LCH   | resourceloader            | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | rustic                    | 1.1.7                | rustic-1.1.7.jar                                      | None                                     |
       | LCH   | rusticthaumaturgy         | 4.4a                 | Rustic+Thaumaturgy-4.4a.jar                           | None                                     |
       | LCH   | scalingguis               | @VERSION@            | scalingguis-1.12.2-1.0.3.0.jar                        | None                                     |
       | LCH   | scavenge                  | 1.8                  | Scavenge+V1.12-1.8.3.2.jar                            | None                                     |
       | LCH   | scavenge_timing           | 1.12.2-1.0           | Scavenge-Timing-1.12.2-1.0.jar                        | None                                     |
       | LCH   | t3s4ebw                   | 1.0                  | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar          | None                                     |
       | LCH   | sqpatch                   | 1.0.0                | SqueezerPatch-1.12.2-1.0.0.jar                        | None                                     |
       | LCH   | tcresearchpatcher         | 1.12.2-1.1.3         | ThaumcraftResearchPatcher-1.12.2-1.1.3.jar            | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCH   | tg                        | 0.1.5.0              | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar              | None                                     |
       | LCH   | thaumadditions            | 12.6.7               | ThaumicAdditions-1.12.2-12.6.7.jar                    | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | thaumicaugmentation       | 1.12.2-2.1.5         | ThaumicAugmentation-1.12.2-2.1.4.jar                  | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCH   | thaumicbases              | 3.3.500.6r           | thaumicbases-fixed-3.3.500.6.2r.jar                   | None                                     |
       | LCH   | thaumicbrewing            | 1.0.2                | thaumicbrewing-1.0.2.jar                              | None                                     |
       | LCH   | thaumicjei                | 1.6.0                | ThaumicJEI-1.12.2-1.6.0-27.jar                        | None                                     |
       | LCH   | thaumicenergistics        | 2.2.3                | thaumicenergistics-v2.2.3-alex811-fork-SNAPSHOT-2.jar | None                                     |
       | LCH   | tcinventoryscan           | 2.0.10               | ThaumicInventoryScanning_1.12.2-2.0.10.jar            | None                                     |
       | LCH   | thaumicrestoration        | 1.5.0                | ThaumicRestoration-1.5.0.jar                          | None                                     |
       | LCH   | thaumictinkerer           | 1.12.2-5.0-620a0c5   | thaumictinkerer-1.12.2-5.0-620a0c5.jar                | None                                     |
       | LCH   | thaumicwonders            | 1.8.2                | thaumicwonders-1.8.2.jar                              | None                                     |
       | LCH   | timestages                | 1.2.1                | Time-Stages-1.12.2-1.4.jar                            | None                                     |
       | LCH   | togetherforever           | 1.0.2                | togetherforever-1.12.2-1.0.12-22.jar                  | None                                     |
       | LCH   | topography                | 1.14.4               | Topography-1.12.2-1.14.4.jar                          | None                                     |
       | LCH   | treetweaker               | 1.6.1                | treetweaker-1.6.1.jar                                 | None                                     |
       | LCH   | uniquecrops               | 0.2.6                | uniquecrops-1.12.2-0.2.6.jar                          | None                                     |
       | LCH   | unlimitedchiselworks      | 0.3.5                | UnlimitedChiselWorks-0.3.5.jar                        | None                                     |
       | LCH   | vanillafix                | 1.0.10-150           | VanillaFix-1.0.10-150.jar                             | None                                     |
       | LCH   | wizardryfates             | 2.1.0                | WizardryFates-2.1.0.jar                               | None                                     |
       | LCH   | zenutils                  | 1.8.3                | zenutils-1.8.3.jar                                    | None                                     |
       | LCH   | zettaigrimoires           | 1.5.0                | ZettaiGrimoires-1.5.0.jar                             | None                                     |
       | LCH   | rf-capability-adapter     | 1.1.3                | capabilityadapter-1.1.3.jar                           | None                                     |
       | LCH   | mospells                  | 1.0.2                | MoSpells-1.12.2-1.0.2.jar                             | None                                     |
       | LCH   | librarianliblate          | 4.22                 | librarianlib-1.12.2-4.22.jar                          | None                                     |
       | LCH   | mysticallib               | 1.12.2-1.13.0        | mysticallib-1.12.2-1.13.0.jar                         | None                                     |
       | LCH   | ocsensors                 | 1.0.4                | ocsensors-1.0.4-b23.jar                               | None                                     |
  Loaded coremods (and transformers): IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      AALoadingPlugin (arcanearchives-0.2.0.25-mixins8.jar)
                                        
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      AnotherCommonBugFix (AnotherCommonBugFix.jar)
                                        com.anotherera.core.ACBFClassTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      SqueezerCore (SqueezerPatch-1.12.2-1.0.0.jar)
                                        shadows.squeezer.Transformer
                                      StackUpCore (StackUp-0.2.5.jar)
                                        pl.asie.stackup.core.StackUpTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      HCASM (HammerLib-1.12.2-2.0.6.31.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.4.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      MixinBooter (mixinbooter-3.2.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
                                        thecodex6824.tcresearchpatcher.Transformer
                                      Botania Tweaks Core (botaniatweaks-1.9.1.jar)
                                        quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
                                      FTBUltimineASM (ftb-ultimine-1202.3.5.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      IntegratedProxy Loading Plugin (integrated_proxy-1.12-1.0.14.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      non_update (NonUpdate-AllMCVersion-Final-2.0.2-universal.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.12.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      AstralCore (astralsorcery-1.12.2-1.10.27.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.4-SNAPSHOT-thin.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      gugu-utils-core (gugu-utils-0.8.1.2.jar)
                                        com.warmthdawn.mod.gugu_utils.asm.common.GuGuAsmTransformer
                                      JechCore (JustEnoughCharacters-1.12.0-3.5.1.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 497.29' Renderer: 'NVIDIA GeForce RTX 2070 Super/PCIe/SSE2'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  HammerCore Debug Information: Dependent Mods:
                                -Botanic Additions (botanicadds) @ 12.2.6
                                -Thaumic Additions: Reconstructed (thaumadditions) @ 12.6.7
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
  Patchouli open book context: n/a
  Suspected Mods: Planar Artifice (planarartifice)
  Launched Version: 神秘复兴：星瀚再临
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2070 Super/PCIe/SSE2 GL version 4.6.0 NVIDIA 497.29, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

```

**Comment by prodzpod** [comment]
oh wow i didnt know there's more mods that use antimony, will fix
