### ISSUE TITLE
conflict with tinkers?

### ISSUE THREAD

**Issue by triggerdepressed** [Zokonius/planar-artifice#9]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Planar Artifice (planarartifice)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "bismuth": It was already registered by MMDLib
    at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:986)
    at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:131)
    at slimeknights.tconstruct.library.MaterialIntegration.preInit(MaterialIntegration.java:101)
    at leppa.planarartifice.compat.tconstruct.TConstructHandler.preInit(TConstructHandler.java:74)
    at leppa.planarartifice.compat.PACompatHandler.lambda$preInit$1(PACompatHandler.java:37)
    at leppa.planarartifice.compat.PACompatHandler$$Lambda$2286/000000000000000000.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at leppa.planarartifice.compat.PACompatHandler.preInit(PACompatHandler.java:37)
    at leppa.planarartifice.main.CommonProxy.preInit(CommonProxy.java:31)
    at leppa.planarartifice.client.ClientProxy.preInit(ClientProxy.java:38)
    at leppa.planarartifice.main.PlanarArtifice.preInit(PlanarArtifice.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by NeroAzure** [comment]
AFAIK thats a conflict with MMDLib, to fix it, I disabled bismuth in MMDLib config.

**Comment by prodzpod** [comment]
this happened because the mod didn't check if the material already existed (i.e. added from other mods), I have made it so other mods can override it.
